// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: price/aggregated/v1/aggregated.proto

package aggregatedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType is event category for a value.
type Response_Type int32

const (
	// Unknown type.
	Response_TYPE_UNSPECIFIED Response_Type = 0
	// BEST_ASK type.
	Response_TYPE_BEST_ASK Response_Type = 1
	// BEST_BID type.
	Response_TYPE_BEST_BID Response_Type = 2
)

// Enum value maps for Response_Type.
var (
	Response_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_BEST_ASK",
		2: "TYPE_BEST_BID",
	}
	Response_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_BEST_ASK":    1,
		"TYPE_BEST_BID":    2,
	}
)

func (x Response_Type) Enum() *Response_Type {
	p := new(Response_Type)
	*p = x
	return p
}

func (x Response_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_price_aggregated_v1_aggregated_proto_enumTypes[0].Descriptor()
}

func (Response_Type) Type() protoreflect.EnumType {
	return &file_price_aggregated_v1_aggregated_proto_enumTypes[0]
}

func (x Response_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Type.Descriptor instead.
func (Response_Type) EnumDescriptor() ([]byte, []int) {
	return file_price_aggregated_v1_aggregated_proto_rawDescGZIP(), []int{1, 0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Instrument class. See https://docs.kaiko.com/?python#instruments.
	InstrumentClass string `protobuf:"bytes,1,opt,name=instrument_class,json=instrumentClass,proto3" json:"instrument_class,omitempty"`
	// Instrument code. See https://docs.kaiko.com/?python#instruments.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_aggregated_v1_aggregated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_price_aggregated_v1_aggregated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_price_aggregated_v1_aggregated_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetInstrumentClass() string {
	if x != nil {
		return x.InstrumentClass
	}
	return ""
}

func (x *Request) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Aggregate (interval).
	Aggregate string `protobuf:"bytes,1,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	// Instrument class. See https://docs.kaiko.com/?python#instruments.
	InstrumentClass string `protobuf:"bytes,2,opt,name=instrument_class,json=instrumentClass,proto3" json:"instrument_class,omitempty"`
	// Instrument code. See https://docs.kaiko.com/?python#instruments.
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// Value is update value (price and volume). Field is absent if the ticker has no update during the aggregate inerval.
	Value *Value `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// Event type is ASK or BID.
	EventType Response_Type `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3,enum=price.aggregated.v1.Response_Type" json:"event_type,omitempty"`
	// Timestamp of event.
	TsEvent *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_aggregated_v1_aggregated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_price_aggregated_v1_aggregated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_price_aggregated_v1_aggregated_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetAggregate() string {
	if x != nil {
		return x.Aggregate
	}
	return ""
}

func (x *Response) GetInstrumentClass() string {
	if x != nil {
		return x.InstrumentClass
	}
	return ""
}

func (x *Response) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Response) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Response) GetEventType() Response_Type {
	if x != nil {
		return x.EventType
	}
	return Response_TYPE_UNSPECIFIED
}

func (x *Response) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Price of top of book entry.
	Price string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	// Volume of top of book entry.
	Volume string `protobuf:"bytes,2,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_aggregated_v1_aggregated_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_price_aggregated_v1_aggregated_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_price_aggregated_v1_aggregated_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Value) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

var File_price_aggregated_v1_aggregated_proto protoreflect.FileDescriptor

var file_price_aggregated_v1_aggregated_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xd7, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x12, 0x29, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x61,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x74, 0x73, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x07, 0x74, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x42, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x42, 0x45, 0x53, 0x54, 0x5f, 0x41, 0x53, 0x4b, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x45, 0x53, 0x54, 0x5f, 0x42, 0x49, 0x44, 0x10, 0x02,
	0x22, 0x35, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x7d, 0x0a, 0x22, 0x63, 0x6f, 0x6d, 0x2e, 0x6b,
	0x61, 0x69, 0x6b, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e,
	0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x48, 0x01, 0x50,
	0x01, 0x5a, 0x32, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x64, 0x76, 0x31, 0xaa, 0x02, 0x1e, 0x4b, 0x61, 0x69, 0x6b, 0x6f, 0x2e, 0x47, 0x52,
	0x50, 0x43, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x64, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_price_aggregated_v1_aggregated_proto_rawDescOnce sync.Once
	file_price_aggregated_v1_aggregated_proto_rawDescData = file_price_aggregated_v1_aggregated_proto_rawDesc
)

func file_price_aggregated_v1_aggregated_proto_rawDescGZIP() []byte {
	file_price_aggregated_v1_aggregated_proto_rawDescOnce.Do(func() {
		file_price_aggregated_v1_aggregated_proto_rawDescData = protoimpl.X.CompressGZIP(file_price_aggregated_v1_aggregated_proto_rawDescData)
	})
	return file_price_aggregated_v1_aggregated_proto_rawDescData
}

var file_price_aggregated_v1_aggregated_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_price_aggregated_v1_aggregated_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_price_aggregated_v1_aggregated_proto_goTypes = []interface{}{
	(Response_Type)(0),            // 0: price.aggregated.v1.Response.Type
	(*Request)(nil),               // 1: price.aggregated.v1.Request
	(*Response)(nil),              // 2: price.aggregated.v1.Response
	(*Value)(nil),                 // 3: price.aggregated.v1.Value
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_price_aggregated_v1_aggregated_proto_depIdxs = []int32{
	3, // 0: price.aggregated.v1.Response.value:type_name -> price.aggregated.v1.Value
	0, // 1: price.aggregated.v1.Response.event_type:type_name -> price.aggregated.v1.Response.Type
	4, // 2: price.aggregated.v1.Response.ts_event:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_price_aggregated_v1_aggregated_proto_init() }
func file_price_aggregated_v1_aggregated_proto_init() {
	if File_price_aggregated_v1_aggregated_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_price_aggregated_v1_aggregated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_aggregated_v1_aggregated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_aggregated_v1_aggregated_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_price_aggregated_v1_aggregated_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_price_aggregated_v1_aggregated_proto_goTypes,
		DependencyIndexes: file_price_aggregated_v1_aggregated_proto_depIdxs,
		EnumInfos:         file_price_aggregated_v1_aggregated_proto_enumTypes,
		MessageInfos:      file_price_aggregated_v1_aggregated_proto_msgTypes,
	}.Build()
	File_price_aggregated_v1_aggregated_proto = out.File
	file_price_aggregated_v1_aggregated_proto_rawDesc = nil
	file_price_aggregated_v1_aggregated_proto_goTypes = nil
	file_price_aggregated_v1_aggregated_proto_depIdxs = nil
}
