// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: index/v1/index.proto

package indexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1 "kaiko.com/go/grpc/core/v1"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Commodity int32

const (
	// Unknown commodity.
	Commodity_COMMODITY_UNSPECIFIED Commodity = 0
	// REAL_TIME commodity.
	Commodity_COMMODITY_REAL_TIME Commodity = 1
	// DAILY_FIXING commodity.
	Commodity_COMMODITY_DAILY_FIXING Commodity = 2
)

// Enum value maps for Commodity.
var (
	Commodity_name = map[int32]string{
		0: "COMMODITY_UNSPECIFIED",
		1: "COMMODITY_REAL_TIME",
		2: "COMMODITY_DAILY_FIXING",
	}
	Commodity_value = map[string]int32{
		"COMMODITY_UNSPECIFIED":  0,
		"COMMODITY_REAL_TIME":    1,
		"COMMODITY_DAILY_FIXING": 2,
	}
)

func (x Commodity) Enum() *Commodity {
	p := new(Commodity)
	*p = x
	return p
}

func (x Commodity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Commodity) Descriptor() protoreflect.EnumDescriptor {
	return file_index_v1_index_proto_enumTypes[0].Descriptor()
}

func (Commodity) Type() protoreflect.EnumType {
	return &file_index_v1_index_proto_enumTypes[0]
}

func (x Commodity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Commodity.Descriptor instead.
func (Commodity) EnumDescriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Index code.
	IndexCode string `protobuf:"bytes,1,opt,name=index_code,json=indexCode,proto3" json:"index_code,omitempty"`
	// Enum indicating type of feed.
	Commodities []Commodity `protobuf:"varint,2,rep,packed,name=commodities,proto3,enum=index.v1.Commodity" json:"commodities,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_v1_index_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_index_v1_index_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetIndexCode() string {
	if x != nil {
		return x.IndexCode
	}
	return ""
}

func (x *Request) GetCommodities() []Commodity {
	if x != nil {
		return x.Commodities
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Index code.
	IndexCode string `protobuf:"bytes,1,opt,name=index_code,json=indexCode,proto3" json:"index_code,omitempty"`
	// Event type.
	Commodity Commodity `protobuf:"varint,2,opt,name=commodity,proto3,enum=index.v1.Commodity" json:"commodity,omitempty"`
	// Data interval.
	Interval *v1.DataInterval `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// Quote.
	Quote string `protobuf:"bytes,4,opt,name=quote,proto3" json:"quote,omitempty"`
	// Bases.
	Bases []*ResponseBaseAsset `protobuf:"bytes,5,rep,name=bases,proto3" json:"bases,omitempty"`
	// Exchanges.
	Exchanges []string `protobuf:"bytes,6,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	// Detailed computation by percentage.
	Percentages []*ResponsePercentage `protobuf:"bytes,7,rep,name=percentages,proto3" json:"percentages,omitempty"`
	// Event generation timestamp (event created by Kaiko), after normalization.
	TsEvent *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ts_event,json=tsEvent,proto3" json:"ts_event,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_v1_index_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_index_v1_index_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetIndexCode() string {
	if x != nil {
		return x.IndexCode
	}
	return ""
}

func (x *Response) GetCommodity() Commodity {
	if x != nil {
		return x.Commodity
	}
	return Commodity_COMMODITY_UNSPECIFIED
}

func (x *Response) GetInterval() *v1.DataInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *Response) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *Response) GetBases() []*ResponseBaseAsset {
	if x != nil {
		return x.Bases
	}
	return nil
}

func (x *Response) GetExchanges() []string {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *Response) GetPercentages() []*ResponsePercentage {
	if x != nil {
		return x.Percentages
	}
	return nil
}

func (x *Response) GetTsEvent() *timestamppb.Timestamp {
	if x != nil {
		return x.TsEvent
	}
	return nil
}

type ResponsePercentage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Percentage.
	Percentage float64 `protobuf:"fixed64,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	// Price computed for the whole percentage.
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	// Detailed computation by pairs.
	Pairs []*ResponsePairs `protobuf:"bytes,3,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *ResponsePercentage) Reset() {
	*x = ResponsePercentage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_v1_index_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePercentage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePercentage) ProtoMessage() {}

func (x *ResponsePercentage) ProtoReflect() protoreflect.Message {
	mi := &file_index_v1_index_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePercentage.ProtoReflect.Descriptor instead.
func (*ResponsePercentage) Descriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{2}
}

func (x *ResponsePercentage) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ResponsePercentage) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ResponsePercentage) GetPairs() []*ResponsePairs {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type ResponsePairs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Pair.
	Pair string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	// Weight (for multiple assets indices).
	Weight float64 `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// Detailed computation by instruments.
	Instruments []*ResponseInstruments `protobuf:"bytes,3,rep,name=instruments,proto3" json:"instruments,omitempty"`
}

func (x *ResponsePairs) Reset() {
	*x = ResponsePairs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_v1_index_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePairs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePairs) ProtoMessage() {}

func (x *ResponsePairs) ProtoReflect() protoreflect.Message {
	mi := &file_index_v1_index_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePairs.ProtoReflect.Descriptor instead.
func (*ResponsePairs) Descriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{3}
}

func (x *ResponsePairs) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *ResponsePairs) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ResponsePairs) GetInstruments() []*ResponseInstruments {
	if x != nil {
		return x.Instruments
	}
	return nil
}

type ResponseInstruments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Exchange.
	Exchange string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Price.
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	// Volume.
	Volume float64 `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *ResponseInstruments) Reset() {
	*x = ResponseInstruments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_v1_index_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseInstruments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseInstruments) ProtoMessage() {}

func (x *ResponseInstruments) ProtoReflect() protoreflect.Message {
	mi := &file_index_v1_index_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseInstruments.ProtoReflect.Descriptor instead.
func (*ResponseInstruments) Descriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseInstruments) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *ResponseInstruments) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ResponseInstruments) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type ResponseBaseAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Asset.
	Asset string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	// Weight.
	Weight float64 `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *ResponseBaseAsset) Reset() {
	*x = ResponseBaseAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_index_v1_index_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseBaseAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBaseAsset) ProtoMessage() {}

func (x *ResponseBaseAsset) ProtoReflect() protoreflect.Message {
	mi := &file_index_v1_index_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBaseAsset.ProtoReflect.Descriptor instead.
func (*ResponseBaseAsset) Descriptor() ([]byte, []int) {
	return file_index_v1_index_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseBaseAsset) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *ResponseBaseAsset) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_index_v1_index_proto protoreflect.FileDescriptor

var file_index_v1_index_proto_rawDesc = []byte{
	0x0a, 0x14, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31,
	0x1a, 0x12, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x35, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0xed, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x69, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x31,
	0x0a, 0x05, 0x62, 0x61, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x05, 0x62, 0x61, 0x73, 0x65,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12,
	0x3e, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x73, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61,
	0x67, 0x65, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x35, 0x0a, 0x08, 0x74, 0x73, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x74,
	0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x79, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0a, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72,
	0x73, 0x22, 0x7c, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x69,
	0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x3f,
	0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x5f, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x22, 0x41, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x61, 0x73, 0x65,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x2a, 0x5b, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79,
	0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x44, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x43,
	0x4f, 0x4d, 0x4d, 0x4f, 0x44, 0x49, 0x54, 0x59, 0x5f, 0x52, 0x45, 0x41, 0x4c, 0x5f, 0x54, 0x49,
	0x4d, 0x45, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x44, 0x49, 0x54,
	0x59, 0x5f, 0x44, 0x41, 0x49, 0x4c, 0x59, 0x5f, 0x46, 0x49, 0x58, 0x49, 0x4e, 0x47, 0x10, 0x02,
	0x42, 0x57, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x48, 0x01, 0x50, 0x01, 0x5a,
	0x22, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x3b, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x76, 0x31, 0xaa, 0x02, 0x13, 0x4b, 0x61, 0x69, 0x6b, 0x6f, 0x2e, 0x47, 0x52, 0x50, 0x43,
	0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_index_v1_index_proto_rawDescOnce sync.Once
	file_index_v1_index_proto_rawDescData = file_index_v1_index_proto_rawDesc
)

func file_index_v1_index_proto_rawDescGZIP() []byte {
	file_index_v1_index_proto_rawDescOnce.Do(func() {
		file_index_v1_index_proto_rawDescData = protoimpl.X.CompressGZIP(file_index_v1_index_proto_rawDescData)
	})
	return file_index_v1_index_proto_rawDescData
}

var file_index_v1_index_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_index_v1_index_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_index_v1_index_proto_goTypes = []interface{}{
	(Commodity)(0),                // 0: index.v1.Commodity
	(*Request)(nil),               // 1: index.v1.Request
	(*Response)(nil),              // 2: index.v1.Response
	(*ResponsePercentage)(nil),    // 3: index.v1.ResponsePercentage
	(*ResponsePairs)(nil),         // 4: index.v1.ResponsePairs
	(*ResponseInstruments)(nil),   // 5: index.v1.ResponseInstruments
	(*ResponseBaseAsset)(nil),     // 6: index.v1.ResponseBaseAsset
	(*v1.DataInterval)(nil),       // 7: core.v1.DataInterval
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_index_v1_index_proto_depIdxs = []int32{
	0, // 0: index.v1.Request.commodities:type_name -> index.v1.Commodity
	0, // 1: index.v1.Response.commodity:type_name -> index.v1.Commodity
	7, // 2: index.v1.Response.interval:type_name -> core.v1.DataInterval
	6, // 3: index.v1.Response.bases:type_name -> index.v1.ResponseBaseAsset
	3, // 4: index.v1.Response.percentages:type_name -> index.v1.ResponsePercentage
	8, // 5: index.v1.Response.ts_event:type_name -> google.protobuf.Timestamp
	4, // 6: index.v1.ResponsePercentage.pairs:type_name -> index.v1.ResponsePairs
	5, // 7: index.v1.ResponsePairs.instruments:type_name -> index.v1.ResponseInstruments
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_index_v1_index_proto_init() }
func file_index_v1_index_proto_init() {
	if File_index_v1_index_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_index_v1_index_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_v1_index_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_v1_index_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePercentage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_v1_index_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePairs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_v1_index_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseInstruments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_index_v1_index_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseBaseAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_index_v1_index_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_index_v1_index_proto_goTypes,
		DependencyIndexes: file_index_v1_index_proto_depIdxs,
		EnumInfos:         file_index_v1_index_proto_enumTypes,
		MessageInfos:      file_index_v1_index_proto_msgTypes,
	}.Build()
	File_index_v1_index_proto = out.File
	file_index_v1_index_proto_rawDesc = nil
	file_index_v1_index_proto_goTypes = nil
	file_index_v1_index_proto_depIdxs = nil
}
