concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - uses: golangci/golangci-lint-action@v3
        with:
          skip-build-cache: true
          skip-go-installation: true
          skip-pkg-cache: true
          version: v1.45
    strategy:
      matrix:
        go-version: [1.18.x]

name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: read
  pull-requests: read
